### ISSUE TITLE
Cum de predai DSA?

### ISSUE THREAD

**Issue by buzea** [bogdansalau/dsa-2021-g3#1]

**Comment by bogdansalau** [comment]
Am incercat cu FP si mi-a placut. Am zis sa trec la ceva mai de baza. Vrei sa vii ca invitat special la un laborator?

**Comment by buzea** [comment]
Sa pui inregistrarile pe youtube sa te vad!

**Comment by bogdansalau** [comment]
The best I can offer is a Git tutorial :)) Check it out in the README.md.
